using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using LIFES.Authentication;

namespace LIFES.UserInterfaces
{
    /*
     * Class Name: GetNewPasswordForm.cs
     * 
     * Author: Riley Smith
     * Date: 4/15/2015
     * Modified by: Riley Smith
     * 
     * Description: This is the driver class for the GetNewPassword Window.
     * 
     *   Initially generated by Visual Studio GUI builder.
     */
    public partial class GetNewPasswordForm : Form
    {
        private string username;

        public GetNewPasswordForm(string name)
        {
            InitializeComponent();

            username = name;
        }

        /*
         * Method: SetPasswordButton_Click
         * Parameters: object Sender, EventArgs e
         * Output: N/A
         * Created By: Riley Smith
         * Date: 4/15/2015
         * Modified By: Riley Smith
         * 
         * Description: Event handler for the Set Password Button.
         */
        private void SetPasswordButton_Click(object sender, EventArgs e)
        {
            UserList userList = new UserList();

            if (passwordTextBox.Text != "" && confirmTextBox.Text != "")
            {
                if (passwordTextBox.Text == confirmTextBox.Text)
                {
                    userList.ChangePassword(username, passwordTextBox.Text);
                    MessageBox.Show("Password for " + username + " changed to: " + passwordTextBox.Text);
                }
            }
        }
    }
}
