using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using LIFES.Authentication;
using System.Text.RegularExpressions;

namespace LIFES.UserInterfaces
{
    /*
     * Class Name: GetNewPasswordForm.cs
     * 
     * Author: Riley Smith
     * Date: 4/15/2015
     * Modified by: Riley Smith
     * 
     * Description: This is the driver class for the GetNewPassword Window.
     * 
     *   Initially generated by Visual Studio GUI builder.
     */
    public partial class GetNewPasswordForm : Form
    {
        private string username;

        public GetNewPasswordForm(string name)
        {
            InitializeComponent();

            username = name;
        }

        /*
         * Method: SetPasswordButton_Click
         * Parameters: object Sender, EventArgs e
         * Output: N/A
         * Created By: Riley Smith
         * Date: 4/15/2015
         * Modified By: Riley Smith
         * 
         * Description: Event handler for the Set Password Button.
         */
        private void SetPasswordButton_Click(object sender, EventArgs e)
        {
            UserList userList = new UserList();
            Regex pwdEx = new Regex("^[a-z]{1}([a-z0-9\\*#\\$]){6,8}$");

            if (passwordTextBox.Text != "" && confirmTextBox.Text != "")
            {
                if (passwordTextBox.Text == confirmTextBox.Text)
                {
                    if (pwdEx.IsMatch(passwordTextBox.Text.ToLower()))
                    {
                        userList.ChangePassword(username, passwordTextBox.Text);
                        MessageBox.Show("Password for " + username + " changed to: " + passwordTextBox.Text);
                    }

                    else
                    {
                        MessageBox.Show("Passwords must be between 7-9\n" +
                            "characters, start with a letter, all be in the\n" +
                            "same case and must contain any of the following\n"+
                            "numbers/leters/#*$");
                    }
                }

                else
                {
                    MessageBox.Show("Please ensure the passwords match.");
                }
            }
        }
    }
}
