using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace LIFES.UserInterfaces
{
  /*
   * Class Name: LoginForm.cs
   * Author: Riley Smith
   * Date: 3/26/2015
   * Modified by: Riley Smith
   * 
   * Description: This is the driver class for the Login GUI Window.
   * 
   * Initially generated by Visual Studio GUI builder.
   */
    public partial class LoginForm : Form
    {
        public LoginForm()
        {
            InitializeComponent();
        }

        private void LoginForm_Load(object sender, EventArgs e)
        {

        }
    }
}
