using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Runtime.InteropServices;
using LIFES.Authentication;

namespace LIFES.UserInterfaces
{
    /*
     * Class Name: LoginForm.cs
     * Author: Riley Smith
     * Date: 3/26/2015
     * Modified by: Riley Smith
     * 
     * Description: This is the driver class for the Login GUI Window.
     * 
     * Initially generated by Visual Studio GUI builder.
     */
    public partial class LoginForm : Form
    {
        //Constants Used for transition animations
        const int AW_SLIDE = 0X40000;
        const int AW_CENTER = 0x00000010;
        const int AW_HOR_POSITIVE = 0X1;
        const int AW_HOR_NEGATIVE = 0X2;
        const int AW_BLEND = 0X80000;

        [DllImport("user32")]
        static extern bool AnimateWindow(IntPtr hwnd, int time, int flags);

        public LoginForm()
        {
            InitializeComponent();
        }

        private void LoginForm_Load(object sender, EventArgs e)
        {

        }

        /*
         * Method: OnLoad
         * Parameters: EventArgs e
         * Output: N/A
         * Created By: Riley Smith
         * Date: 3/30/2015
         * Modified By: Riley Smith
         * 
         * Override the function that loads the Form.
         * Animates the window as it opens.
         */
        protected override void OnLoad(EventArgs e)
        {
            AnimateWindow(this.Handle, 200, AW_CENTER | AW_HOR_POSITIVE);
        }

        /*
         * Method: Login
         * Parameters: object sender, EventArgs s
         * Output: N/A
         * Created By: Scott Smoke
         * Date: 4/12/2015
         * Modified By: Scott Smoke
         * 
         * Description: This will grab the username and password
         * from their respective text boxes and see if they are valid. 
         */ 
        private void Login(object sender, EventArgs e)
        {
            string userName = userNameTextBox.Text;
            string pwd = passwordTextBox.Text;
            UserList users = new UserList();
            //if userName is in the file
            //then if pwd is equal to password stored in the file
            //then log on
            //else throw error(s)

            if (users.TestPassword(userName, pwd))
            {
                MessageBox.Show("Login Success");
            }

            else 
            {
                MessageBox.Show("Login Failed");
            }

        }
    }
}
