using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using LIFES.FileIO;
namespace LIFES.UserInterfaces
{
    public partial class MainGUI : Form
    {
        public MainGUI()
        {
            InitializeComponent();

            scheduleButton.Click += Schedule_Click;
            rescheduleButton.Click += Reschedule_Click;
            timeConstraintsButton.Click += TimeConstraintsButton_Click;
            enrollmentButton.Click += EnrollmentButton_Click;
        }

        /*
         * Method: EnrollmentButton_Click
         * Parameters: object sender, EventArgs e
         * Output: N/A
         * Created By: Riley Smith
         * Date: 3/24/2015
         * Modified By: Riley Smith
         * 
         * Event handler for the button Total Enrollment 
         */
        void EnrollmentButton_Click(object sender, EventArgs e)
        {
            EnrollmentForm enrollmentGUI = new EnrollmentForm();
            enrollmentGUI.ShowDialog();

            textTest.Text = "Clicked Total Enrollment Button";
        }

        /*
         * Method: TimeConstraintsButton_Click
         * Parameters: object sender, EventArgs e
         * Output: N/A
         * Created By: Riley Smith
         * Date: 3/24/2015
         * Modified By: Riley Smith
         * 
         * Event handler for the button Time Contraints
         */
        void TimeConstraintsButton_Click(object sender, EventArgs e)
        {

            TimeConstraintsForm timeConstraintsGUI = new TimeConstraintsForm();
            timeConstraintsGUI.ShowDialog();
            TimeConstraints tc = timeConstraintsGUI.GetTimeConstraints();

            //Testing
            if (tc != null)
            {
                textTest.Text = tc.GetNumberOfDays().ToString();
            }
            else
            {
                textTest.Text = "Error getting data";
            }
          
        }

        /*
         * Method: Reschedule_Click
         * Parameters: object sender, EventArgs e
         * Output: N/A
         * Created By: Riley Smith
         * Date: 3/24/2015
         * Modified By: Riley Smith
         * 
         * Event handler for the button Reschedule
         */
        void Reschedule_Click(object sender, EventArgs e)
        {
            textTest.Text = "Clicked Reschedule Button";
        }

        /*
         * Method: Schedule_Click
         * Parameters: object sender, EventArgs e
         * Output: N/A
         * Created By: Riley Smith
         * Date: 3/24/2015
         * Modified By: Riley Smith
         * 
         * Event handler for the button Schedule
         */
        void Schedule_Click(object sender, EventArgs e)
        {
            examTable.Rows[0].Cells[0].Value = "First Class Time";
            examTable.Rows[0].Cells[1].Value = "First Exam Time";
 
            textTest.Text = "Clicked Schedule Button";
        }


        // All this was generated by visual
        private void richTextBox1_TextChanged(object sender, EventArgs e)
        {

        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {

        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void textTest_TextChanged(object sender, EventArgs e)
        {

        }
        /*
         * Method: SaveAsToolStripMenuItem_Click
         * Parameters: object sender, EventArgs e
         * Output: A filed saved in the requested format.
         * Created By: Scott Smoke
         * Date: 3/26/2015
         * Modified By: Scott Smoke
         * This will allow the user to enter a file name and a save file type.
         * Source: msdn.microsoft.com
         *         http://stackoverflow.com/questions/11964955/how-to-check-what-filter-is-applied
         */
        private void SaveAsToolStripMenuItem_Click(object sender, EventArgs e)
        {
            SaveFileDialog saveFile = new SaveFileDialog();
            saveFile.Filter = "txt files (*.txt)| *.txt|" +
            "Comma Sperateve Values (*.csv) |*.csv| pdf (*.pdf) |*.pdf";
            saveFile.ShowDialog();
            FileOut outFile = new FileOut(saveFile.FileName);
            switch(saveFile.FilterIndex)
            {
                case 1:
                    //write to text file
                    outFile.WriteToText();
                    break;
                case 2:
                    outFile.WriteToCSV();
                    break;
                case 3:
                    outFile.WriteToPDF();
                    break;
                default:
                    //error
                    break;


            }
            
        }
    }
}

